name: Enigm
main: fr.modofuzeiii.enigm.EnigmMain
version: 2.0
author: Wistaro & King
commands:
    ehelp:
        description: Help players
        permission: help.use
    etest:
        description: Test
        permission: test.use
    a:
<<<<<<< HEAD
        description: Message de broadcast par le plugin Enigm
        permission: test.use
    egm:
        description: Donne des items administrateurs au joueur
        permission: egm.use
=======
        description: Broadcast Message
        permission: a.use
    estart:
        description: Starting Game
        permission: estart.use
    estop:
        description: Stopping Game
        permission: estop.use
    epause:
        description: Pausing Game
        permission: epause.use
>>>>>>> b9ecebbaf041fc425a7cf89ccf392047a6cfeeb8
