name: Enigm
main: fr.modofuzeiii.enigm.EnigmMain
version: 2.0
api-version: 1.14
author: Wistaro & King
commands:
    ehelp:
        description: Help players
        permission: help.use
    etest:
        description: Test
        permission: test.use
    egm:
        description: Admin Tools
        permission: egm.use
    a:    
        description: Broadcast Message
        permission: a.use
    estart:
        description: Starting Game
        permission: estart.use
    estop:
        description: Stopping Game
        permission: estop.use
    epause:
        description: Pausing Game
        permission: epause.use
    pts:
        description: Manage enigm team points
        permission: pts.use
    teams:
        description: Manage enigm teams
        permission: teams.use
